metadata.json
Fix module name, using hyphen separator as documented at https://docs.puppetlabs.com/puppet/latest/reference/modules_publishing.html#another-note-on-module-names, rather than non-standard slash, which confuses some tools.
Version number will need to be bumped when this is published.
Relates to PDB-1115
=> Fix separator in module name in metadata.json

Gemfile
Seems rspec 3.2.0 broke on Ruby 1.8.7. This does a pinning so we can avoid the
issue.
=> Pin rspec to 3.1.7 so we avoid the ruby 1.8.7 errrors

lib/puppet/provider/puppetdb_conn_validator/puppet_https.rb
This commit addresses an issue where the provider for
puppetConnValidator was not using the test_url specified by the
resource. This commit passes the param from the initializer to the utils
class.
=> (bugfix) Use test_url in connection validator for puppetdb

manifests/params.pp
This commit adds conditionals to use `$settings::confdir` to introspect
the value for `$puppet_confdir` when available. This change is necessary
for compatibility with the path changes in Puppet 4.
=> (PDB-1353) Use settings::confdir for puppet_confdir

CHANGELOG, metadata.json
Version bump to build a version without `._` files.
=> (MODULES-1917) Ignore `._` files when building the module tarball

.fixtures.yml, Gemfile, spec/unit/util/puppetdb_validator_spec.rb
This fixes the file_concat dependency issue postgresql module has brought in,
plus bumps some other dependencies and removes some deprecation warnings from
our tests.
=> (maint) Add file_concat and bump rspec versions

README.md, manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/config_ini.pp, spec/unit/classes/server/config_ini_spec.rb
with regard to the command-processing section.
Added new class server/config_ini.pp to manage contents of the config.ini.
Three new parameters added:
* command_threads
* store_usage
* temp_usage
All three default to 'undef'. This makes sure (potential) custom settings
done to that file with regard to above three variables are 'absent',
and let PuppetDB built-in defaults take care.
Documentation to the README.md added, as well as unit tests.
My use-case was, that I have on some nodes a too small /var partition,
so I had to lower the values of store-usage and temp-usage in the config.ini
manually.
=> Enable the module to manage entries in $confdir/config.ini

manifests/server.pp
This fixes the ordering for the read_database_ini class, and fixes a small
notification problem with config_ini as well.
=> (PDB-1467) Ordering problem with read_database_ini

manifests/params.pp, spec/unit/classes/server/jetty_ini_spec.rb
This was changes in the package, but never reflected in the module.
=> (maint) Change default ssl-host to 0.0.0.0

manifests/init.pp
This commit fixes a bug where if a user tried to turn off database
validation there would be a `before` statement requiring an absent
validation resource.
=> (maint) Allow database_validation to be false

README.md, lib/puppet/util/puppetdb_validator.rb, manifests/master/config.pp, manifests/master/puppetdb_conf.pp, manifests/params.pp, spec/unit/classes/master/config_spec.rb, spec/unit/util/puppetdb_validator_spec.rb
This commit changes the terminus configuration to use the new root
prefix for PuppetDB and changes the connection validator to do the same.
=> (PDB-1035) Add default PuppetDB root context

README.md, manifests/master/config.pp, manifests/master/puppetdb_conf.pp, manifests/params.pp, manifests/server.pp, spec/unit/classes/master/config_spec.rb, spec/unit/classes/master/puppetdb_conf_spec.rb
This commit adds the ability to manage to legacy style of terminus for
`PuppetDB 2.x`.
=> (maint) Add ability to manage old terminus style

CHANGELOG, metadata.json
This commit updates metadata.json to be version 5.0.0 for the module and
puts todays date as the release date for the module.
=> (PDB-1620) Change metadata for version 5

manifests/database/postgresql.pp, manifests/init.pp
Useful for when this module wants to install PGDG postgresql-9.4 on a CentOS 7 system with postgresql 9.2 already running (e.g. foreman)
=> Fix unmanaged postgresql database port

manifests/params.pp, manifests/server.pp, manifests/server/command_processing.pp, manifests/server/database.pp, manifests/server/global.pp, manifests/server/jetty.pp, manifests/server/read_database.pp, spec/unit/classes/server/command_processing_spec.rb, spec/unit/classes/server/database_ini_spec.rb, spec/unit/classes/server/db_connection_uri_spec.rb, spec/unit/classes/server/global_ini_spec.rb, spec/unit/classes/server/jetty_ini_spec.rb
This updates the module to manage vardir, and also makes room for general
management of the global ini section.
=> (PDB-1913) manage vardir

manifests/server/firewall.pp
Use of "port" is deprecated and adds a too relaxed firewall rule to the system:
https://github.com/roman-mueller/puppetlabs-firewall/commit/4f2df97faab93e530ff5a4d99afa3d9d16a246cd
It will also be removed in the future.
Use dport instead in the manifest.
=> MODULES-2488 Use dport instead of the now deprecated port parameter

manifests/globals.pp, manifests/init.pp, manifests/master/routes.pp, manifests/params.pp, manifests/server.pp, manifests/server/database.pp, manifests/server/global.pp, manifests/server/read_database.pp
This patch fixes some of the lint warnings/errors we've been getting on the
forge.
In some cases I've fixed real bugs also, in particular double quotes/single
quotes in cases, which would have broken variable interpolation.
=> (maint) Lint fixes

README.md, manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/puppetdb.pp, spec/unit/classes/server/puppetdb_ini_spec.rb, templates/certificate-whitelist.erb
Set up a certificate whitelist file and configure it in PuppetDB so that
only the Puppet master has access by default.
=> Restrict access to the Puppet master by default

manifests/params.pp, spec/unit/classes/master/config_spec.rb
This makes it possible to upgrade PDB from 2.x to 3+ on redhat without
explicitly specifying the terminus package name.
=> (maint) use 'puppetdb-terminus' on redhat with version 3+

Gemfile, manifests/master/config.pp, spec/unit/classes/master/config_spec.rb
This commit adds an exec to allow users to upgrade to termini-3.x via the
module with no extra manual steps.
=> (maint) Handle terminus to termini package upgrades

CHANGELOG, README.md, metadata.json
This commit adds release notes and some README cleanups for a v5.1.2
release of the module for the CentOS terminus upgrade fix.
=> (maint) Prep module for v5.1.2 release

README.md
changed in commit 448f8bc996b4e797ef463b1c2b89710374d9fd19
=> open_ssl_listen_port defaults to undef, not true

spec/unit/classes/init_spec.rb, spec/unit/classes/master/config_spec.rb, spec/unit/classes/master/puppetdb_conf_spec.rb, spec/unit/classes/server_spec.rb
The firewall module requires selinux and the iptables_persistent_version facts to be defined
up front for our tests to pass. This patch includes those static facts, so we pass.
=> (PDB-2637) Add static facts for selinux and iptables to fix rspec tests

manifests/database/postgresql.pp
postgresql contrib package is needed to avoid warn message about pg_trgm indexes
=> Update postgresql.pp with postgresql contrib package

.gitignore, manifests/server.pp, manifests/server/command_processing.pp, manifests/server/database.pp, manifests/server/global.pp, manifests/server/jetty.pp, manifests/server/puppetdb.pp, manifests/server/read_database.pp, spec/unit/classes/init_spec.rb, spec/unit/classes/server/database_ini_spec.rb, spec/unit/classes/server/global_ini_spec.rb, spec/unit/classes/server/jetty_ini_spec.rb, spec/unit/classes/server/puppetdb_ini_spec.rb, spec/unit/classes/server/read_database_ini_spec.rb, spec/unit/classes/server_spec.rb
Much like read-database.ini, we need to ensure the permissions for puppetdb.ini are set explicitly
to ensure permissions are still correct after configuration. Without this users with different umask
settings may find their files are no longer accessible after the module runs.
=> (PDB-2571) Ensure puppetdb.ini file has correct permissions

manifests/params.pp
Seems since end of April/beginning of May, with the
permission changes of puppetdb config ini files,
it is broken on OpenBSD.
This fixes is by setting the $puppetdb_user, and
$puppetdb_group in OS specific case statements:
Some more info:
underprivileged users from packages start with
_underscore, as well as such groups, therefore on OpenBSD, the
user:group is _puppetdb:_puppetdb
Because of that, instead of the single default in params.pp,
move the definition of puppetdb_user and puppetdb_group into
one of the OS specific case statement.
As a side node not 100% related:
I wonder why the config files have to be owned by
the puppetdb user/group?
From a security point of view, wouldn't it make more sense,
to have the config files owned by root:$puppetdb_group, and
permissions like 640? IIRC, …
=> FIX: Unbreak on OpenBSD

README.md
The basic 3-node setup example in the documentation assigns some variables for the 3 nodes and then tries to resolve these variables in the node statements. However, puppet complains of a syntax error when it reaches the variable just after the `node` keyword.
`puppet parser validate` also indicates that code is not valid.
The puppet language reference says...
>A node statement’s name must be one of the following:
>    A quoted string containing only letters, numbers, underscores (_), hyphens (-), and periods (.).
>    A regular expression.
>    The bare word default.
Newbies (like I am) reading the examples might get confused (like I did). :-)
=> replace invalid node name variables in 3-node example

README.md
PuppetDB 4.0 no longer supports the embedded database. We need to be more explicit about that.
=> Strengthen warning against the embedded db

spec/unit/classes/init_spec.rb, spec/unit/classes/master/config_spec.rb, spec/unit/classes/master/puppetdb_conf_spec.rb, spec/unit/classes/master/report_processor_spec.rb, spec/unit/classes/server/command_processing_spec.rb, spec/unit/classes/server/database_ini_spec.rb, spec/unit/classes/server/read_database_ini_spec.rb, spec/unit/classes/server_spec.rb
A recent change in puppetlabs-apt requires us to set this explicitly to avoid a
lookup error.
=> (PDB-3032) add puppetversion fact in spec tests

.travis.yml, Gemfile
The Puppet AIO is going to start using ruby 2.3.1 and as such needs to
be supported here.
=> Add support for Ruby 2.3.1

README.md
We already had noted that HSQL was no longer supported, but we still
had examples of using it in the docs and didn't call it out in the db
configuration section. This commit fixes that.
=> (PDB-2614) Remove HSQL example add another disclaimer on it's usage

.gitignore, .travis.yml, Gemfile, manifests/database/postgresql.pp, manifests/params.pp, metadata.json, spec/acceptance/basic_spec.rb, spec/acceptance/nodesets/docker/centos-7.yml, spec/acceptance/nodesets/docker/debian-8.yml, spec/acceptance/nodesets/docker/ubuntu-14.04.yml, spec/default_facts.yml, spec/spec_helper.rb, spec/spec_helper_acceptance.rb, spec/unit/classes/init_spec.rb, spec/unit/classes/master/config_spec.rb, spec/unit/classes/master/puppetdb_conf_spec.rb, spec/unit/classes/master/report_processor_spec.rb, spec/unit/classes/server_spec.rb
Casts `$database_port` in `postgresql.pp` to an integer to make module compatible with `puppetlabs-postgresql` 5.x
Fix an issue where `puppetlabs-puppetdb` would pass `true` to `managed_pg_repo` by default for all supported OSes, however `puppetlabs-postgresql` can only manage the pg repo if the `osfamily` is RedHat or Debian.
Added rspec-puppet-facts to the unit tests and updated the beaker tests with beaker-puppet_install_helper and beaker-module_install_helper. These simplify test setup (it also happened to be the easiest way to get tests working consistently).
=> (PDB-3587) Add puppetlabs-postgresql 5.x support and integrate rspec-puppetfacts

metadata.json, spec/acceptance/basic_spec.rb, spec/spec_helper_acceptance.rb
aac71812f6da18e402c8082d9627a37152943c75 added this dependency but it's only needed in the acceptance tests.
=> Move ntp dependency to spec_helper_acceptance

README.md, manifests/master/config.pp, spec/unit/classes/master/config_spec.rb
The `defined(Service[$puppet_service_name])` pattern in this module is parse-order dependent, and I was unable to declare a `service { 'puppetserver' ...}` in some code I was writing because this module was parsed first and had already declared the resource.
To work around this, I've added a parameter to the class, which defaults to the existing behavior of `true` so it won't break existing behavior for anyone. However, one can override this to `false` which skips the creation of the `$puppet_service_name` service resource in this module and thereby avoids a duplicate resource error when compiling the catalog.
=> Fix duplicate resource errors for puppet service due to parse order

README.md
This fixes the rendering of the headers in the README on GitHub, and also fixes the PostgreSQL version mentioned since the default is now 9.6, not 9.4.
=> README: Fixes for postgres default version and header rendering

manifests/database/postgresql.pp
The dependency to the database is missing. This should be explicitly added. `postgresql::server::extension` does not add the dependency automatically, because the database is definded below, after the extension,  so the defined() check does not work. https://github.com/puppetlabs/puppetlabs-postgresql/blob/34aa0affa233e04a25c3b4d130e6db867bff08bd/manifests/server/extension.pp#L48-L50
```
postgresql::server::extension { 'pg_trgm':
database  => $database_name,
require   => Postgresql::Server::Db[$database_name],
}
```
related to #271
=> add explicit dependency db -> extension.

manifests/database/postgresql.pp, spec/acceptance/nodesets/docker/ubuntu-14.04.yml, spec/spec_helper_acceptance.rb
* working on getting travis tests going with PG 9.6 before bumping version dep
=> (PDB-3654) bump version and ini file dep

manifests/server.pp, spec/unit/classes/server_spec.rb, templates/puppetdb-DLO-cleanup.service.epp
Previously, the DLO path was hardcoded in with its default value. This
means that when attempting to clean a DLO store on a system using a
non-default location for vardir, the puppetdb module would attempt to
remove a directory that was not actually the DLO store (if it existed at
all).
Now, in accordance with how puppetdb selects the DLO store location, the
puppetdb module will use `<vardir>/stockpile/discard/` as the DLO
location.
=> (PDB-4092) Use vardir prefix for DLO path

README.md, manifests/master/config.pp, manifests/master/storeconfigs.pp
(MODULES-9905) Create enable_storeconfigs option for puppet::master::config
This creates a flag to allow the removal of 'storeconfigs' and 'storeconfigs_backend' directives from puppet.conf when those directives are managed by the module.
No tests are included here because there was no unit test to begin with(?!).
=> Create enable_storeconfigs option for puppet::master::config

manifests/master/routes.pp, spec/unit/classes/master/config_spec.rb
Puppetserver 7 now defaults the fact cache to json[1]. When running in
agent-server mode, configure routes.yaml the same way. There is no change in
behavior when running with puppetserver < 7 or `puppet apply`.
As a result of this change, when the puppetdb module is used to install the
puppetdb terminus and routes.yaml, facts will now be cached as non-pretty json
in:
/opt/puppetlabs/server/data/puppetserver/server_data/facts/<node>.json
Instead of pretty yaml in:
/opt/puppetlabs/server/data/puppetserver/yaml/<node>.yaml
The difference in pathing is due to the abstract yaml and json termini using
different base directories in which to store data: `Puppet[:yamldir]` vs
`Puppet[:server_data]`.
[1] https://github.com/puppetlabs/puppetserver/blob/794e725628545aa075e3f8b5fa91f21628373594/src/rub …
=> (PDB-4945) Default to json fact cache

README.md
Version 1.1 has been archived, suggest linking to latest instead to be safe.
=> Fix reference to PuppetDB documentation

metadata.json
This allows us to pick up the dnf changes added in [puppetlabs-postgres/pr/1239](https://github.com/puppetlabs/puppetlabs-postgresql/pull/1239) which addresses issues installing postgres on el8.
=> (SERVER-2500) Allow puppetlabs-postgresql 7.x

metadata.json
`metadata.json` update to allow the current versions of the inifile, firewall, and stdlib modules.
=> allow current versions of inifile, firewall, stdlib

README.md
The TTL values from the readme do not correspond to those [configured by the module](MOD) and are the [default values from PuppetDB](PDB).
Adjust the README so that it describes the actual configuration.
[MOD]: https://github.com/puppetlabs/puppetlabs-puppetdb/blob/11dc0dfd91b26e9babc31b0221cd2442ae1b46a9/manifests/params.pp#L40-L43
[PDB]: https://puppet.com/docs/puppetdb/latest/configure.html#node-ttl
=> Sync TTL default values in the README with actual defaults

README.md, manifests/database/default_read_grant.pp, manifests/database/postgresql.pp, manifests/database/postgresql_ssl_rules.pp, manifests/database/read_grant.pp, manifests/database/read_only_user.pp, manifests/database/ssl_configuration.pp, manifests/init.pp, manifests/params.pp, manifests/server.pp, manifests/server/database.pp, manifests/server/read_database.pp, spec/acceptance/basic_spec.rb, spec/unit/classes/database/ssl_configuration_spec.rb, spec/unit/classes/server/db_read_uri_spec.rb, spec/unit/classes/server/read_database_ini_spec.rb
There used to be only one user (puppetdb) which was used for all operations on the database.
This PR adds a read only user in PostgreSQL which will be used only for queries.
=> (maint) Add read-only user.

metadata.json
https://github.com/puppetlabs/puppetlabs-puppetdb/pull/330 uses the
namespaced `postgresql::postgresql_password` function that wasn't
available until 6.5.0.
(Even before that PR, I doubt this module worked with
puppetlabs/postgresql 4.0.0 released in 2014).
=> Fix minimum version of puppetlabs/postgresql

.fixtures.yml, metadata.json
Per [github](https://github.blog/2021-09-01-improving-git-protocol-security-github/), "unencrypted git:// offers no integrity or authentication, [...] We’ll be disabling support for this protocol."
This switches the protocols to https:// which they indicate is unaffected.
=> Update github URLs to remove unauthenticated git

metadata.json
This brings compatibility with newer Debian versions where there is no contrib package.
=> Mark as compatible with puppetlabs/postgresql 8.x

manifests/database/postgresql.pp
Fix for https://tickets.puppetlabs.com/browse/PDB-5454
_Started a new PR (to avoid license issue)_
=> postgresql version >=10 onwards does not require contrib package

manifests/database/postgresql.pp
Reverts puppetlabs/puppetlabs-puppetdb#350
reverting because it was merfed by accident
=> Revert "postgresql version >=10 onwards does not require contrib package"

manifests/globals.pp, manifests/master/config.pp, manifests/params.pp
This allows to test control-repos catalogs with onceover using factsets
that do not include legacy facts.
=> Fix legacy fact usage

manifests/server/global.pp
The puppetdb user doesn't need to write to the config (it's managed by Puppet after all) so setting the owner to root and using the group to only read is safer.
It is also closer to packaging, which ensures the owner is root after a package update. Ideally packaging would use the same group and mode as well so there isn't an event after a package update, but this change at least trims it down from 3 changes to 2.
=> Set owner of server config.ini to root

manifests/server.pp
Fixes 010bf136c78ff84c54903322505aaca6af3d13f8
=> Fix "has no parameter named 'puppetdb_user'"

manifests/globals.pp, manifests/params.pp
$settings::<> vars should generally be configurable because they hold the compilers value. This can be a problem if for example you're trying to use this module with Bolt, which returns a temp directory.
I'm not a fan of the globals (or params) class, but this gets the job done in lieu of overhauling the module to meet current standards.
_Hopefully issues can be enabled soon so we can start collaborating on bringing this module into the current century._
=> make puppet_confdir configurable

manifests/params.pp
While the code has some code related to FreeBSD, the module is not functional on this platform.
This PR fix the FreeBSD support and allows using this module on this OS.
=> Fix FreeBSD support

manifests/database/postgresql.pp, manifests/database/postgresql_ssl_rules.pp, manifests/database/ssl_configuration.pp, spec/defines/database/postgresql_ssl_rules_spec.rb, spec/support/unit/shared/database.rb, spec/unit/classes/database/ssl_configuration_spec.rb
12 and up, that is.
PuppetDB 8.0.0 requires Postgresql 14 or later, but starting in 12 the syntax for the clientcert option in pg_hba.conf changed. This PR implements the new syntax when a newer version of Postgresql is requested by the user.
=> use the correct value for clientcert in pg_hba.conf for Postgresql 12

manifests/database/default_read_grant.pp, spec/support/unit/shared/database.rb
puppetdb in default config will create a read-only user, however there is a bug[1] with the syntax to set the default read grant.
Fix it with help from comments[2].
[1] https://github.com/puppetlabs/puppetlabs-puppetdb/pull/330#issuecomment-935496488
[2] https://github.com/puppetlabs/puppetlabs-puppetdb/pull/339#issuecomment-1163552126
=> Fix: Unterminated quoted string when creating read user

.fixtures.yml, manifests/server/firewall.pp, metadata.json, spec/support/unit/shared/server.rb
As part of the Firewall module rewrite the functionality of the `action` attribute has been rolled into the `jump` attribute, the two of them both managing the Firewall jump value.
=> (BACKWARDS-INCOMPATIBLE) Update firewall manifests to use `jump` instead of `action`

.fixtures.yml, manifests/params.pp, metadata.json, spec/acceptance/standalone_spec.rb, spec/support/acceptance/shared/puppetdb.rb, spec/support/unit/shared/database.rb, spec/unit/classes/database/postgresql_spec.rb
Postgres 11 is no longer supported as an installation method from Postgres.org. As a result, installations will fail using `puppetlabs-postgresql` with failures like:
```
Error: /Stage[main]/Postgresql::Server::Install/Package[postgresql-server]/ensure: change from 'purged' to 'present' failed: Execution of '/usr/bin/yum -d 0 -e 0 -y install postgresql11-server' returned 1: One of the configured repositories failed (PostgreSQL 11 7 - x86_64),
and yum doesn't have enough cached data to continue. At this point the only
safe thing yum can do is fail. There are a few ways to work "fix" this:
1. Contact the upstream for the repository and get them to fix the problem.
2. Reconfigure the baseurl/etc. for the repository, to point to a working
upstream. This is most often useful if you are using a …
```
=> Change default postgres version to 14

manifests/database/default_read_grant.pp, manifests/database/postgresql.pp, manifests/database/read_grant.pp, manifests/database/read_only_user.pp, spec/acceptance/standalone_spec.rb, spec/defines/database/default_read_grant_spec.rb, spec/defines/database/read_grant_spec.rb, spec/defines/database/read_only_user_spec.rb, spec/support/acceptance/shared/puppetdb.rb, spec/unit/classes/database/postgresql_spec.rb
Very helpful to be able to switch ports on a major version change.
Found while testing upgrading from 7.14.0 to 8.0.0 (to be released) of this module
Testing also revealed, deploying to an existing setup (eg. puppetdb + postgresql 11), postgresql 14 server will be deployed but unable to start (port in use by postgresql 11).
=> Fix custom database port support

metadata.json
puppetlabs/firewall has moved up to 8.x, mark this as allowed to use it.
=> Allow puppetlabs/firewall 8.x

HISTORY.md
When preparing a new release of the module, GCG overrite the whole
CHANGELOG.md file, but it used to be crafted by hand and we do not want
to loose this information.
GCG can append an existing file to the generated changelog, and if this
file is properly formatted, can guess which versions are covered by this
HISTORY file to not include them again.
Move the CHANGELOG.md to HISTORY.md and adjust the release lines so that
GCG can properly parse the first one and the following ones are
formatted the same way.  The resulting CHANGELOG.md which will be
generated on the next release preparation will be consistently
formatted.
=> Archive CHANGELOG.md

manifests/database/postgresql.pp, manifests/database/read_only_user.pp, manifests/init.pp, manifests/params.pp, metadata.json, spec/unit/classes/init_spec.rb
PostgreSQL module uses by default `scram-sha-256` password [encryption for PostgreSQL databases since 14](https://github.com/puppetlabs/puppetlabs-postgresql/commit/43c21aff1a1e07d8bdc2da211e3503a973ae4034) - introduced in `puppetlabs-postgresql == 10.1.0`. At least `puppetlabs-postgresql >= 9.2` [is needed](https://github.com/puppetlabs/puppetlabs-postgresql/commit/985309e2df83aa16b1b5430ef1607eca56981de7). 
This PR introduces new parameter `postgresql_password_encryption`, to apply the old (less secure behavior) use:
```yaml
puppetdb::postgresql_password_encryption: 'md5'
```
In order to use modern password auth, the hba rules and password function requires passing the `password_encryption` parameter.
Related issues: 
- #394
=> Support scram-sha-256 password_encryption method

metadata.json
The changes introduced in #392 require changes that where introduced in
version 10.0.0 of the puppetlabs-postgresql module, but the lower
version of the module was not properly updated in this PR.
Fix the lower bound of the dependency to indicate that version 10 of the
puppetlabs-postgresql module is required for proper operation.
Fixes #401
=> Fix lower bound the of puppetlabs-postgresql dependency

lib/facter/puppetdb_version.rb, spec/unit/facter/puppetdb_version_spec.rb
The code changes add a new Facter fact called `puppetdb_version` that retrieves the version of PuppetDB installed on the system. It uses the `puppetdb --version` command to fetch the version and returns it as a fact value.
=> Add a `puppetdb_version` fact with PuppetDB version

manifests/server.pp, manifests/server/database.pp, manifests/server/jetty.pp, manifests/server/puppetdb.pp, manifests/server/read_database.pp, spec/unit/classes/server/database_ini_spec.rb, spec/unit/classes/server/jetty_ini_spec.rb, spec/unit/classes/server/puppetdb_ini_spec.rb, spec/unit/classes/server/read_database_ini_spec.rb, spec/unit/classes/server_spec.rb
PuppetDB runs as the puppetdb user.  This user must have read access to the various configuration files but does not need write access to them.
This ensure the service configuration cannot be unexpectedly changed by PuppetDB itself if some vulnerability allow random code execution, limiting the possibilities of exploitation and pivoting if such a vulnerability is found.
This is a companion PR to #342: the FreeBSD port insists on secure file permissions and will enforce them when the service start.  On next Puppet run, the module will consider it configuration drift and revert the previous less paranoid configuration and reload the service which will harden the files mode immediatly.  Rather than optionaly ignoning the files mode, it makes more sense to use an hardened configuration by …
=> Restrict configuration file permissions

manifests/server.pp
Fixes the following error
Error: /Stage[main]/Puppetdb::Server/Cron[puppetdb-dlo-cleanup]: Could not evaluate: Cannot write the puppetdb user's crontab: The user does not exist
=> cron puppetdb-dlo-cleanup requires package

manifests/database/postgresql.pp, spec/unit/classes/database/postgresql_spec.rb
According to the [docs](https://puppet.com/docs/puppetdb/7/configure_postgres.html) you should specify the encoding when creating the database. The database encoding will be set depending on your locale (I got LATIN1) unless specified.
I am getting some errors is the PuppetDB logs: 
```
ERROR: unsupported Unicode escape sequence Detail: Unicode escape values cannot be used for code point values above 007F when the server encoding is not UTF8.
```
and filling up few gig of additional log at `/opt/puppetlabs/server/data/puppetdb/stockpile/discard`
=> set encoding when creating the DB

lib/facter/puppetdb_version.rb, spec/unit/facter/puppetdb_version_spec.rb
i tried to get around the debian package differences and report a version also if this package is used. sadly somehow i didnt get `puppetdb version` running on my ubuntu testbox. so i tried to get the version from the package itself if it is not the puppetlabs one.
fixes: #413
=> Extend fact to not fail on debian packages
